alias python3=python

alias ga='git add'
alias gc='git commit -m'
alias gs='git status'
alias gp='git push origin'
alias gl='git pull origin'
alias gcm='git checkout main && git pull origin main && git branch -d '
alias gd='git diff'
alias gds='git diff --staged'
alias gr='git reset HEAD --hard'
alias ls='ls -F'
alias ll='ls -lh'
alias mnt="mount | awk -F' ' '{ printf \"%s\t%s\n\",\$1,\$3; }' | column -t | egrep ^/dev/ | sort"
alias hg='history|grep'  # search bash history, I swapped the letters for github-cli compatibility
alias left='ls -t -1'  # most recently edited files
alias cg='cd `git rev-parse --show-toplevel`'  # go to git main level
